# -*- coding: utf-8 -*-
"""Orientation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1T_ns1aW38T9XSIQrihcM0i-JWSvs2i

Example of addition
"""

a = 2
b = 3
c = 2+3
print(c)

"""Example of string"""

Greetings= "Advice na, pror"
print(Greetings)